In [1]:
from hurobo.utils.notebook import setup_notebook

ROOT = setup_notebook()

# Our fine-tuned SmolVLA against the two pretrained LIBERO checkpoints

Four policies on the **same scene** (LIBERO's table and robot, cleared, with the bowl and plate at their real, scaled sizes: the `scaled` condition) and the **same layouts**:

| Policy | Weights |
|---|---|
| ours, `smolvla_base` init | `lerobot/smolvla_base` fine-tuned on our 100 generated episodes (action expert only); the best of its checkpoints |
| ours, `smolvla_libero` init | `lerobot/smolvla_libero` fine-tuned on the same data with the same settings; the best of its checkpoints |
| `HuggingFaceVLA/smolvla_libero` | pretrained, used as is |
| `lerobot/smolvla_libero` | pretrained, used as is |

Modules: `hurobo.model_comparison`, `hurobo.checkpoint_eval`, `hurobo.policy_rollout`. Real data only: 12 real clips (7 passing the QC gates, 5 with the release-distance gate waived) turned into 100 robot episodes.

**How the best checkpoint is chosen.** By closed-loop success on layouts 0 to 9 (ties: lower open-loop error). It is then compared on **held-out layouts 100 and up**, so it is not judged on the episodes it was picked on. The two pretrained policies are run on the same held-out layouts. All policies use the same episode limit and replan interval. The sample is small, so read the intervals, not just the bars.

In [2]:
from hurobo.checkpoint_eval import checkpoint_table
from hurobo.model_comparison import ModelComparison, fine_tuned_contender
from hurobo.policy_rollout import KNOWN_CHECKPOINTS
from hurobo.real_setup import DEFAULT_MEASUREMENTS, RealSetup

FINAL_STEP = 3000
RUNS = {
    "ours, smolvla_base init": (ROOT / "outputs/e1_smolvla_ckpts/run", ROOT / "results/smolvla_ckpts"),
    "ours, smolvla_libero init": (
        ROOT / "outputs/e1_smolvla_libero_init/run",
        ROOT / "results/smolvla_libero_init_ckpts",
    ),
}
contenders = []
for label, (run_dir, results_dir) in RUNS.items():
    try:
        contenders.append(fine_tuned_contender(label, run_dir, results_dir, FINAL_STEP))
    except ValueError as reason:
        print(f"not entered: {label}: {reason}")
contenders += [KNOWN_CHECKPOINTS["hfvla"], KNOWN_CHECKPOINTS["lerobot"]]
print([spec.name for spec in contenders])

['ours, smolvla_base init (step 2500)', 'ours, smolvla_libero init (step 2500)', 'HuggingFaceVLA/smolvla_libero', 'lerobot/smolvla_libero']

## How each training run progressed

Closed-loop success per checkpoint step (layouts 0 to 9, 10 episodes each) with the 95 % Wilson interval. This is what the best checkpoint is picked from.

In [3]:
from hurobo.utils.comparison_view import progress_figure

progress_figure({label: checkpoint_table(results) for label, (_, results) in RUNS.items()}).show()

## Closed loop on held-out layouts, scaled scene

In [4]:
from hurobo.utils.comparison_view import success_figure

comparison = ModelComparison(RealSetup.load(DEFAULT_MEASUREMENTS), ROOT / "results/smolvla_compare")
summary = comparison.run(contenders, episodes=20)
summary[
    [
        "checkpoint",
        "episodes",
        "successes",
        "success_rate",
        "ci_low",
        "ci_high",
        "lifted",
        "mean_steps_success",
    ]
]

[robosuite WARNING] No private macro file found! (__init__.py:7)

WARNING:robosuite_logs:No private macro file found!

[robosuite WARNING] It is recommended to use a private macro file (__init__.py:8)

WARNING:robosuite_logs:It is recommended to use a private macro file

[robosuite WARNING] To setup, run: python /home/eeschner/alfredo/workspace/hurobo/.venv/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py (__init__.py:9)

WARNING:robosuite_logs:To setup, run: python /home/eeschner/alfredo/workspace/hurobo/.venv/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py

Creating LIBERO envs | suites=['libero_goal'] | n_envs(per task)=1 | init_states=True
Restricting to task_ids=[8]
[info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Built vec env | suite=libero_goal | task_id=8 | n_envs=1

Loading  HuggingFaceTB/SmolVLM2-500M-Video-Instruct weights ...

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Reducing the number of VLM layers to 16 ...

Loading weights from local directory

Loading  HuggingFaceTB/SmolVLM2-500M-Video-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Reducing the number of VLM layers to 16 ...

Loading weights from local directory

Local assets not found. Downloading from HuggingFace Hub...
Assets already downloaded at /home/eeschner/.cache/libero/assets

/home/eeschner/alfredo/workspace/hurobo/.venv/lib/python3.12/site-packages/robosuite/utils/binding_utils.py:1010: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self.qpos[addr] = value

ours, smolvla_libero init (step 2500) ep100: fail

ours, smolvla_libero init (step 2500) ep101: fail

ours, smolvla_libero init (step 2500) ep102: SUCCESS

ours, smolvla_libero init (step 2500) ep103: SUCCESS

ours, smolvla_libero init (step 2500) ep104: SUCCESS

ours, smolvla_libero init (step 2500) ep105: SUCCESS

ours, smolvla_libero init (step 2500) ep106: fail

ours, smolvla_libero init (step 2500) ep107: SUCCESS

ours, smolvla_libero init (step 2500) ep108: fail

ours, smolvla_libero init (step 2500) ep109: SUCCESS

ours, smolvla_libero init (step 2500) ep110: SUCCESS

ours, smolvla_libero init (step 2500) ep111: SUCCESS

ours, smolvla_libero init (step 2500) ep112: SUCCESS

ours, smolvla_libero init (step 2500) ep113: SUCCESS

ours, smolvla_libero init (step 2500) ep114: SUCCESS

ours, smolvla_libero init (step 2500) ep115: SUCCESS

ours, smolvla_libero init (step 2500) ep116: fail

ours, smolvla_libero init (step 2500) ep117: fail

ours, smolvla_libero init (step 2500) ep118: SUCCESS

ours, smolvla_libero init (step 2500) ep119: SUCCESS

Loading  HuggingFaceTB/SmolVLM2-500M-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Loading  HuggingFaceTB/SmolVLM2-500M-Video-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Reducing the number of VLM layers to 16 ...

,checkpoint,episodes,successes,success_rate,ci_low,ci_high,lifted,mean_steps_success
0,HuggingFaceVLA/smolvla_libero,20,0,0.00,0.000000,0.161130,0.00,NaN
1,lerobot/smolvla_libero,20,0,0.00,0.000000,0.161130,0.10,NaN
2,"ours, smolvla_base init (step 2500)",20,3,0.15,0.052368,0.360423,0.55,298.000000
3,"ours, smolvla_libero init (step 2500)",20,14,0.70,0.481023,0.854525,0.75,357.785714

In [5]:
success_figure(summary).show()

## Open loop against the generated data

The error of the predicted action chunk against the demonstrations, on the same sampled frames for every policy. The fine-tuned policies trained on this dataset; the pretrained ones did not, so their error here says how far they are from our demonstrations, not how good they are.

In [6]:
comparison.open_loop(contenders, ROOT / "data/e1/generated_clips").round(3)

Loading  HuggingFaceTB/SmolVLM2-500M-Video-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Reducing the number of VLM layers to 16 ...

Loading weights from local directory

Loading  HuggingFaceTB/SmolVLM2-500M-Video-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Reducing the number of VLM layers to 16 ...

Loading weights from local directory

Loading  HuggingFaceTB/SmolVLM2-500M-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Loading  HuggingFaceTB/SmolVLM2-500M-Video-Instruct weights ...

Loading weights:   0%|          | 0/489 [00:00<?, ?it/s]

Reducing the number of VLM layers to 16 ...

,policy,gripper_accuracy,mae_pos,mae_rot,mae_gripper,do_nothing_mae_pos
0,"ours, smolvla_base init (step 2500)",0.963,0.087,0.004,0.124,0.137
1,"ours, smolvla_libero init (step 2500)",0.969,0.075,0.004,0.093,0.137
2,HuggingFaceVLA/smolvla_libero,0.410,0.266,0.028,1.181,0.137
3,lerobot/smolvla_libero,0.419,0.343,0.027,1.179,0.137

## One held-out episode per policy

In [7]:
from hurobo.utils.notebook import show_video

for spec in contenders:
    print(spec.name)
    show_video(
        next((ROOT / "results/smolvla_compare/videos").glob(f"{spec.name.replace('/', '_')}__ep*.mp4")),
        width=360,
    )

ours, smolvla_base init (step 2500)
ours, smolvla_libero init (step 2500)
HuggingFaceVLA/smolvla_libero
lerobot/smolvla_libero